S02 us22 login account
WildCodeSchool/2023-09-PHP-LYON-meet-n-zik pull request #10
Opened 2023-11-12 21:48 UTC by Thomas-Lunardo

Here is my limit,
You can login yourself with any mail or password.
I need your help to understand how verify that the mail and password are the same as those present inside the database.
See you.

2023-11-13 09:36 UTC, StoicFrenchDev requested changes
If the US isn't fully operational it shouldn't be in a Pull Request.
Share the branch with your team, work on it together if needed and then ask to merge it.

2023-11-13 20:27 UTC, Thomas-Lunardo commented
Now it works.

2023-11-14 15:12 UTC, victorzanotelli approved these changes

2023-11-14 15:40 UTC, Merhene approved these changes

2023-11-15 08:42 UTC, AminaChakirDev commented on src/Controller/UserController.php
> +            }
Il y a un souci au niveau de la hierarchie des validations. 
Tu dois vérifier si ton tableau d'erreur est vide (if (empty($errors)) {) avant de rechercher un user dans la base de données

2023-11-15 08:44 UTC, AminaChakirDev commented on src/Service/FormVerificationService.php
> +                $this->errors[] = "Le mot de passe ne correspond pas ";
Tu donnes trop de détails sur les erreurs. Si le message envoyé est : "le mot de passe ne correspond pas, cela sous-entend qu'un compte est bien créé avec cet email)

2023-11-15 08:44 UTC, AminaChakirDev commented on src/View/signup.html.twig
> +					Verifier les informations saisies
accent sur le "e"

2023-11-15 08:45 UTC, AminaChakirDev commented on src/View/signup.html.twig
> +					<input type="text" id="name" name="name" required placeholder="Eliase">
Eliase en placeholder ?

2023-11-15 09:54 UTC, Thomas-Lunardo commented on src/Service/FormVerificationService.php
> +                $this->errors[] = "Le mot de passe ne correspond pas ";
done

2023-11-15 09:54 UTC, Thomas-Lunardo commented on src/View/signup.html.twig
> +					Verifier les informations saisies
done

2023-11-15 09:55 UTC, Thomas-Lunardo commented on src/View/signup.html.twig
> +					<input type="text" id="name" name="name" required placeholder="Eliase">
Done

2023-11-15 14:12 UTC, merged