S02 us09 ajouter une page apercu profiles
WildCodeSchool/2023-09-PHP-LYON-meet-n-zik pull request #13
Opened 2023-11-16 14:10 UTC by victorzanotelli

2023-11-16 15:20 UTC, StoicFrenchDev requested changes

2023-11-16 15:20 UTC, StoicFrenchDev commented on src/Controller/UserController.php
> +        //return $this->twig->render('HTTP/1.1 401 Unauthorized');
Dead code spotted

2023-11-16 21:09 UTC, Thomas-Lunardo approved these changes

2023-11-20 10:08 UTC, Merhene approved these changes

2023-11-20 10:09 UTC, Thomas-Lunardo approved these changes

2023-11-20 10:25 UTC, StoicFrenchDev requested changes
You haven't removed the dead code that I mentioned 4 days ago.

2023-11-20 11:29 UTC, victorzanotelli reviewed
c'est changéééééééééé !!!!!

2023-11-20 11:35 UTC, StoicFrenchDev approved these changes

2023-11-20 11:35 UTC, merged