S02 us19 create profil page and modification profil page
WildCodeSchool/2023-09-PHP-LYON-meet-n-zik pull request #14
Opened 2023-11-17 22:34 UTC by Thomas-Lunardo

2023-11-19 15:23 UTC, victorzanotelli approved these changes

2023-11-19 19:33 UTC, StoicFrenchDev requested changes

2023-11-19 19:33 UTC, StoicFrenchDev commented on src/View/User/edit-user-profil.html.twig
> +					<iframe width="560" height="315" src="{{ embedLink }}" frameborder="0" allowfullscreen></iframe>
Style goes to CSS file.

2023-11-19 19:33 UTC, StoicFrenchDev commented on src/View/User/user-profil.html.twig
> +				<iframe width="560" height="315" src="{{ embedLink }}" frameborder="0" allowfullscreen></iframe>
Same here

2023-11-19 21:15 UTC, Thomas-Lunardo commented on src/View/User/edit-user-profil.html.twig
> +					<iframe width="560" height="315" src="{{ embedLink }}" frameborder="0" allowfullscreen></iframe>
Done

2023-11-19 21:15 UTC, Thomas-Lunardo commented on src/View/User/user-profil.html.twig
> +				<iframe width="560" height="315" src="{{ embedLink }}" frameborder="0" allowfullscreen></iframe>
Done

2023-11-20 10:18 UTC, victorzanotelli approved these changes

2023-11-20 10:20 UTC, Merhene approved these changes

2023-11-20 10:26 UTC, StoicFrenchDev approved these changes

2023-11-20 10:26 UTC, merged