S01 us08 creation of the registration page
WildCodeSchool/2023-09-PHP-LYON-meet-n-zik pull request #3
Opened 2023-11-04 22:03 UTC by Thomas-Lunardo

2023-11-05 14:56 UTC, Merhene approved these changes

2023-11-05 16:30 UTC, StoicFrenchDev requested changes

2023-11-05 16:30 UTC, StoicFrenchDev commented on src/View/Home/login.html.twig
> +	<div class="container loginPage">
Unclosed div

2023-11-05 16:30 UTC, StoicFrenchDev commented on src/View/Home/login.html.twig
> +				<div class="buttonsLine">
HTML classes should be written this way "buttons-line"

2023-11-05 16:30 UTC, StoicFrenchDev commented on src/View/Home/signup.html.twig
> +	<div class="container signUpPage">
Same here no camelCase for class name

2023-11-05 16:30 UTC, StoicFrenchDev commented on src/View/Home/signup.html.twig
> +					<input type="text" id="UserName" name="UserName" required placeholder="Eliase">
Do not duplicate ids between these two forms.

2023-11-06 13:24 UTC, benrcd requested changes
Update with new develop update first

2023-11-06 16:06 UTC, StoicFrenchDev approved these changes

2023-11-06 16:06 UTC, merged

2023-11-06 16:12 UTC, victorzanotelli reviewed
c'est tout bon